services:
  ghost:
    image: ghost:5-alpine
    restart: unless-stopped
    depends_on:
      ghost-db: { condition: service_healthy }
    environment:
      # Core Ghost configuration
      - NODE_ENV=production
      - url=https://news.${DOMAIN}
      # Database configuration
      - database__client=mysql
      - database__connection__host=ghost-db
      - database__connection__user=${GHOST_DB_USER}
      - database__connection__password=${GHOST_DB_PASSWORD}
      - database__connection__database=${GHOST_DB_DATABASE}
      # Storage paths
      - paths__contentPath=/var/lib/ghost/content
      # Mail configuration
      - mail__transport=SMTP
      - mail__options__host=${GHOST_MAIL_HOST}
      - mail__options__port=465
      - mail__options__auth__user=${GHOST_MAIL_USER}
      - mail__options__auth__pass=${GHOST_MAIL_PASSWORD}
      - mail__options__secureConnection=true
      - mail__options__requireTLS=true
      - mail__from=${GHOST_MAIL_FROM}
      # Disable admin authentication security features
      - security__staffDeviceVerification=false
    volumes:
      - ghost-content:/var/lib/ghost/content
    networks:
      - traefik-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.ghost.rule=Host(`news.${DOMAIN}`)
      - traefik.http.routers.ghost.entrypoints=websecure
      - traefik.http.services.ghost.loadbalancer.server.port=2368
      - traefik.http.routers.ghost.tls=true
      - traefik.http.routers.ghost.tls.certresolver=letsencrypt
      # Security headers
      - traefik.http.routers.ghost.middlewares=ghost-security,ghost-compression
      - traefik.http.middlewares.ghost-security.headers.stsSeconds=31536000
      - traefik.http.middlewares.ghost-security.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.ghost-security.headers.contentTypeNosniff=true
      - traefik.http.middlewares.ghost-security.headers.browserXssFilter=true
      - traefik.http.middlewares.ghost-security.headers.referrerPolicy=strict-origin-when-cross-origin
      - traefik.http.middlewares.ghost-security.headers.frameDeny=true
      # Content compression
      - traefik.http.middlewares.ghost-compression.compress=true

  ghost-db:
    image: mysql:8.0-debian
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${GHOST_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${GHOST_DB_DATABASE}
      MYSQL_USER: ${GHOST_DB_USER}
      MYSQL_PASSWORD: ${GHOST_DB_PASSWORD}
    volumes:
      - ghost-mysql-data:/var/lib/mysql
    networks:
      - traefik-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    labels:
      - traefik.enable=false

volumes:
  ghost-content:
  ghost-mysql-data:

networks:
  traefik-network:
    external: true
